### ISSUE TITLE
Include clickable links to game instructions for all games in the rotation

### ISSUE THREAD

**Issue by erb2000** [ctm/mb2-doc#250]
Make it easy to get to the game description at least for the current game, and preferably for all of the games in the mix (so you can read ahead for the next game up).

**Comment by ctm** [comment]
I've certainly thought of this several times. I don't think it'll be high enough priority to do before BARGE. I'm currently swamped, but I do think it's super important.

Since all the BARGE tournaments will be announced in advance, we can squeak by without this for those tournaments, but if I implement sit-n-goes (#233) then this becomes higher priority since that'll allow people to schedule things w/o advance notice.

**Comment by ctm** [comment]
FWIW, I did add the ability for people to post clickable links in the chat. They syntax is `[caption](url)`, which is the same syntax used in Markdown. As such, anyone can post clickable links to the rules before a tourney starts.

This is obviously a burden and a hack and doesn't scale, so I am not suggesting it's a replacement. However, it's a stopgap and better than nothing.

Doing it automatically for all games isn't that hard, per, se, but it is complicated by the fact that I am going to redo how game options are represented internally and more importantly in the database. That's necessary for #196 and #233.

**Comment by ctm** [comment]
I'm guilty of letting the perfect be the enemy of the good on this one. I know a hacky way that will work in almost all the cases. It's ugly, but I (or someone else when there's more than just me) can refactor it into something better.

**Comment by ctm** [comment]
Ugh. Turns out it's trickier than I thought. Currently I have each of the 44 games as `const`s, although `GAMES` itself is `Lazy`. We can't call destructors from `const` functions, so having an `Option<String>` for the docs info can't be done without turning the games themselves into `Lazy`, which is doable, but ...

There's no linkage between the string that's passed in as part of the `Dealing` table message and the `GameInfo` that's encoded in the `Rounds`. In fact, the client doesn't know what `Round` it's in, per-se. It just knows select attributes that it picks up through other messages.

So, I can get past the first stumbling block, although it does complicate things slightly, but then I'd run smack into the second stumbling block and that really makes it too much trouble to implement today, especially since I got a late start and I have other things for today.

Oh well. At least I can refer to this issue the next time I'm feeling frisky.

**Comment by ctm** [comment]
As a stop-gap, the lobby now has a ridiculous pull-down with links to the rules. Or it will, once my deploy finishes.

**Comment by ctm** [comment]
Thank you, @mzimmers for the suggestion of a link in the lobby. I went with the only slightly more complicated drop-down. It's a bit ugly in terms of it making people scroll and not disappearing immediately after being selected, but it's a lot better than nothing.

**Comment by ctm** [comment]
This can be done in the next interface, but doing it for this interface is not a good use of time.
