### ISSUE TITLE
Redrum: murder, but deuce-to-seven only

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#421]
smalltalkdan suggested this.  I've already implemented it, so I'll be closing this issue after I smoke test.

**Comment by ctm** [comment]
Deploying now.

**Comment by cmecklin** [comment]
I think we've found that redrum really doesn't play that well as a low-only game.  It basically turns into a contest of reading the board to see if you have the nuts.
It might play OK with a high as well.  I suspect flush would be too weak as a qualifier.  This is what IMO makes Archie a better game than Korean--the stricter qualifiers.
What's the rationale for fives full or better, rather than just any full house?

**Comment by ctm** [comment]
My rationale is deuces, treys and fours are super important for getting a low, and when you have a pair of any of them you're kind of cutting into other people's chances for getting a lock low, so this makes those pairs a little weaker, but still playable. Also, presto!

I'm not wed to fives full or higher, but I'm definitely partial to it.
