### ISSUE TITLE
Allow revealing after everyone folds

### ISSUE THREAD

**Issue by kenkubey** [ctm/mb2-doc#426]
Many times, I'd like to reveal my cards if everyone else folds
or if I fold heads-up.

Not always at the river or showdown.

Like I might jam with AK in NLH and want to show it if everyone folds.

**Comment by ctm** [comment]
FWIW, this issue had been subsumed by #411 (see [this comment](https://github.com/ctm/mb2-doc/issues/411#issuecomment-687874818)), but having it be its own issue is a good idea.

I've edited the original title though because "Reveal Anytime" is less descriptive.

As it is, if you are jamming with AK in NLH and you know you want to show it if everyone folds before you jam, all you have to do is type "re" in the command box and that is exactly what will happen. As such, this issue is not about giving players the ability to choose to reveal before the hand is over. This is about giving players the ability to reveal _after_ the showdown code has been invoked, but before the new hand is dealt.

**Comment by ctm** [comment]
Done. Deploying shortly.
