### ISSUE TITLE
Mexican Poker

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#440]
[Mexican Poker](https://poker.fandom.com/wiki/Mexican_Poker) ([another set of rules](https://www.thebike.com/play/poker_mexican_poker.php)) can be implemented in steps:

- [x] Deck with 8, 9, 10 removed, joker
- [x] Appropriate Evaluator
- [x] Stud-like first to act
- [x] Button used for resolving ties on upcard
- [x] Messages for how to receive next dealt card
- [x] Response to those messages

I pretty much have almost all of the pieces, in that mb2 already deals short-deck games with alternate evaluation, so adding a different flavor is no big deal. Similarly, mb2 already has the concept of `RevealableCard` which can be up or down.

FWIW, I'd like to be able to offer this for FARGO, although I can't spend so much time on it that I jeopardize the heads-up event.

**Comment by cmecklin** [comment]
If you don't know, https://www.thebike.com/play/poker_mexican_poker.php
We played this in the 27-Game event when the 26-Game event winner chose it as the new game, but that was the only time and I don't think it was ever in the Rule Book.  The "new" thing from mb2's aspect seems to be in how you will deal with players choosing to expose their down card and making sure the next card dealt is up/down appropriately.
Also see the WSOP Cash Game rules, which had the same stuff on page 19.
https://www.wsop.com/2019/2019%20WSOP%20Live%20Action%20Rules%20(FINAL).pdf

Something that's not in the Rule Book is Super Stud variations, also on page 19 of the WSOP Cash Game rules.  This is stud (or stud/8 or razz) where the players are deal 1 up card and 4 down cards.  After the initial round of betting, players still in the pot discard two of their cards, and the rest of the hand proceeds as a typical stud/stud8/razz hand.  Basically, this makes it so that players have stronger starting hands, and thus the winning hands will tend to be stronger.  I've also seen it played live where players were dealt 3 cards down rather than 4, and discard 1 after the initial betting.

If you think about it, "Irish Poker" is really just "Super Texas Holdem".

**Comment by ctm** [comment]
Thanks @cmecklin! I agree that The Bike's explanation is quite handy. I stumbled across it yesterday evening and edited my description for this issue to include it just so I won't forget.

I wasn't familiar with the WSOP Cash Game rules, so I'll remember that when I go to add more games.

To some extent I wasn't planning on adding more games any time soon, but Mexican Poker became an exception to my plan.

**Comment by ctm** [comment]
Here's the status update I posted on the BARGE mailing list:

> In order to be a little more generic, mb2 now has the concept of exposing cards. In an exposure round, you click on the cards you want to expose and then click a button. It's the same code as we use for discarding or drawing. To some extent that would make sense if there were a variety of cards you could expose, but in Mexican poker, there's only one, so it's a completely horrible way to do things. On top of that, I haven't added any additional feedback to show you which of your cards is exposed. So, the right thing happens with respect to both what other people can see and how your next card is dealt, but it's still quite the shit-show.

> My reasoning for doing the above is that I really just wanted to concentrate on having the right messages go back and forth between the server and the client, and I'm happy with that. There are some fairly easy changes I will make to at least make it clear which of your cards is down, but I want to get the rest of the game mechanics done first.

> If I chose to show the game in its primordial state, it will be for the comedic "before" picture. Of course the "after" picture (as long as I'm doing the UI) will still suck, but at least it will be playable.

**Comment by ctm** [comment]
I'm taking this off High Priority, although I may add it back on in a few minutes ...

**Comment by ctm** [comment]
FWIW, I added "Up" and "Down" buttons, but there's no documentation for them yet, so I've created an issue for that (#449).

**Comment by ctm** [comment]
I think it's sufficiently well implemented that any nits get their own issue.
