### ISSUE TITLE
show the binglaha die roll somewhere

### ISSUE THREAD

**Issue by ctm** [ctm/mb2-doc#468]
> ADBDaVoice 🎤: for the next game Binglaha...any way to put di roll down near Hand count?

FWIW, I thought that would get in the way of the compact representation, because I thought I was at the limit of the amount of small icons that would fit along with command and chat, but chat has its own line, so I guess I'm forgetting how that worked.

So ... there's no reason I couldn't do it.  In fact, I've downloaded six svgs, one for each die face.  I don't know when I'll do this, but

**Comment by DaVoice** [comment]
I'm not sure if it even needs to be a die face.  In the space where you normally would have the draw count for the draw games is there a way to have the interface show HI, LO, or HILO if that were easier?  Otherwise the face svg would be great.
Thanks for the consideration.  I play on my PC and have to scroll up to see the text of the roll each time.
Rick

**Comment by ctm** [comment]
I did this a while ago and forgot to close this issue.
